### ISSUE TITLE
informative: mv overlay

### ISSUE THREAD

**Issue by vaeth** [reith/eselect-net#2]
This is just to inform you that this package is on the list of projects which I watch more or less regularly for new releases for the mv overlay: When you tag a new release, I will usually bump the corresponding version in the mv overlay (after a while when I find time...).

**Comment by reith** [comment]
Thanks Martin!

eselect-net does not create `conf.d` or `devs` directories in `/etc/eselect/net`.  To work properly, they should be created either on module itself (for next tag), or in ebuild.
